# Generated by Django 5.0.6 on 2024-07-04 18:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("travel", "0001_initial"),
        ("travel_account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelOrders",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMFIRMED", "Confired"),
                            ("SHIPPED", "Shipped"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "created_data",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_orders",
                        to="travel_account.travelaccount",
                    ),
                ),
            ],
            options={
                "db_table": "travel_orders",
            },
        ),
        migrations.CreateModel(
            name="TravelOrdersItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "orders",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_order_items",
                        to="travel_orders.travelorders",
                    ),
                ),
                (
                    "travel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="travel.travel"
                    ),
                ),
            ],
            options={
                "db_table": "travel_orders_item",
            },
        ),
    ]
