# Generated by Django 5.0.6 on 2024-07-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Travel",
            fields=[
                ("travelId", models.AutoField(primary_key=True, serialize=False)),
                ("travelName", models.CharField(max_length=128)),
                (
                    "travelPrice",
                    models.DecimalField(decimal_places=2, default="0.0", max_digits=10),
                ),
                ("travelProperty", models.CharField(max_length=128)),
                ("travelContent", models.TextField()),
                ("travelImage", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "travel",
            },
        ),
    ]
