# Generated by Django 5.0.6 on 2024-07-02 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TravelAccount",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "travel_account",
            },
        ),
        migrations.CreateModel(
            name="TravelAccountLoginType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loginType",
                    models.CharField(choices=[("KAKAO", "Kakao")], max_length=10),
                ),
            ],
            options={
                "db_table": "travel_account_login_type",
            },
        ),
        migrations.CreateModel(
            name="TravelAccountRoleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roleType", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "travel_account_role_type",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=64, unique=True)),
                ("email", models.CharField(max_length=64, unique=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="travel_account.travelaccount",
                    ),
                ),
            ],
            options={
                "db_table": "travel_profile",
            },
        ),
        migrations.AddField(
            model_name="travelaccount",
            name="loginType",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="travel_account.travelaccountlogintype",
            ),
        ),
        migrations.AddField(
            model_name="travelaccount",
            name="roleType",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="travel_account.travelaccountroletype",
            ),
        ),
    ]
