# Generated by Django 5.0.6 on 2024-06-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travel_board", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelboard",
            name="reviewImage",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
