# Generated by Django 5.0.6 on 2024-07-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("travel_board", "0002_alter_travelboard_point"),
        ("travel_board", "0002_travelboard_reviewimage"),
    ]

    operations = []
